/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;
import projectmanager.Task;
import projectmanager.Employee;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.util.ArrayList;
import projectmanager.TeamLeader;

/**
 *
 * @author Omar Qabeel
 */
public class Task_AddPanel extends javax.swing.JPanel {

    /**
     * Creates new form Task_AddPanel
     */
    public Task_AddPanel() {
        initComponents();
    }
public static ArrayList<Employee> Employees = new ArrayList<Employee>();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TextF_ID = new javax.swing.JTextField();
        jLabelSucessOrFail = new javax.swing.JLabel();
        btnAddTask = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        TextF_Name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextA_Desc = new javax.swing.JTextArea();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jCheckBox_Completed = new javax.swing.JCheckBox();
        Find_TLid = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel3.setText("Status");

        jLabel5.setText("Task ID");

        jLabelSucessOrFail.setFont(new java.awt.Font("Ebrima", 3, 18)); // NOI18N
        jLabelSucessOrFail.setText("Add New Task ... !");

        btnAddTask.setText("Add Task");
        btnAddTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTaskActionPerformed(evt);
            }
        });

        jLabel6.setText("Employee ID");

        jLabel4.setText("Team Leader ID");

        TextA_Desc.setColumns(20);
        TextA_Desc.setRows(5);
        jScrollPane1.setViewportView(TextA_Desc);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton1.setText("Find");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jCheckBox_Completed.setText("Completed");
        jCheckBox_Completed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_CompletedActionPerformed(evt);
            }
        });

        Find_TLid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Find_TLidActionPerformed(evt);
            }
        });

        jLabel1.setText("Name");

        jLabel2.setText("Describtion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(249, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(jCheckBox_Completed))
                            .addComponent(jLabelSucessOrFail, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(186, 186, 186))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TextF_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Find_TLid)
                                    .addComponent(TextF_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41)
                                .addComponent(jButton1)))
                        .addGap(72, 72, 72))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(409, 409, 409)
                        .addComponent(btnAddTask)))
                .addGap(127, 127, 127))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addComponent(jLabelSucessOrFail, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jButton1)
                    .addComponent(Find_TLid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextF_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextF_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_Completed)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(btnAddTask)
                .addGap(33, 33, 33))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTaskActionPerformed
        // TODO add your handling code here:
        if (!TextF_ID.getText().equals("") && !TextF_Name.getText().equals("") &&  !TextA_Desc.getText().equals("") /*&& !Adress_Text.getText().equals("")*/) {

            Task x = new Task();
            x.setID(Integer.parseInt(TextF_ID.getText()));
            x.setName(TextF_Name.getText());
            x.setDes((TextA_Desc.getText()));
            x.setState(jCheckBox_Completed.isSelected());
            x.AssignTask(Integer.parseInt((String) jComboBox1.getSelectedItem()));

            //            if (x.AssignTask()) {
                //            jLabelSucessOrFail.setText("Added Successfully ... !");
                //            resetPanelData();
                //            } else {
                //            jLabelSucessOrFail.setText("Failed to add ... !");
                //            }
            //            } else {
            //            jLabelSucessOrFail.setText("Missing required Fields ... !  Please, complete them before submit ...!");
            //            }
        //
    }//GEN-LAST:event_btnAddTaskActionPerformed
    }
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (!Find_TLid.getText().equals("")) {
            Employee xx = new Employee();
            TeamLeader x = new TeamLeader();
            TeamLeader returned = x.searchLeader(Integer.parseInt(Find_TLid.getText()));
            if (returned.getID() > 0) {
                Employees = xx.searchByTID(returned.getID());
                setComboEmployees(Employees);
            } else {
                jLabelSucessOrFail.setText("Not Found ...!");
            }
        } else {
            jLabelSucessOrFail.setText("Missing required Fields ... !  Please, Search By ID before submit ...!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox_CompletedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_CompletedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_CompletedActionPerformed

    private void Find_TLidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Find_TLidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Find_TLidActionPerformed

      protected void setComboEmployees(ArrayList<Employee> employees){
        for(int i =0;i<employees.size();i++){
            if(employees.get(i).getTID()== Integer.parseInt(TextF_ID.getText())){
        jComboBox1.addItem(Integer.toString(employees.get(i).getID()));
      }}
    }
        
         protected void resetPanelData() {
        TextF_ID.setText("");
        TextF_Name.setText("");
        TextA_Desc.setText("");
        //ComboBox_Project.set("");

        
        }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Find_TLid;
    private javax.swing.JTextArea TextA_Desc;
    private javax.swing.JTextField TextF_ID;
    private javax.swing.JTextField TextF_Name;
    private javax.swing.JButton btnAddTask;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox_Completed;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelSucessOrFail;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
